spring.application.name=demo

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_invoice
spring.datasource.username=postgres
spring.datasource.password=0901

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# MinIO
# ===============================
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=Minio@123456
minio.bucket-name=invoices