import { useState } from 'react'
import reconciliationService, { type Reconciliation } from '../../services/reconciliationService'
import ContentCard from '../../components/ui/ContentCard'
import EmptyState from '../../components/ui/EmptyState'
import ErrorState from '../../components/ui/ErrorState'
import LoadingState from '../../components/ui/LoadingState'
import PageHeader from '../../components/ui/PageHeader'

const money = (value: number) => Number(value).toLocaleString('vi-VN')
const ReconciliationWorkspace = () => {
 const [documentId,setDocumentId]=useState(''); const [items,setItems]=useState<Reconciliation[]>([]); const [loading,setLoading]=useState(false); const [pending,setPending]=useState<number|null>(null); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [note,setNote]=useState('');
 const id=Number(documentId); const load=async(run:boolean)=>{if(!Number.isInteger(id)||id<1){setError('Nhập mã chứng từ hợp lệ.');return}setLoading(true);setError('');try{setItems(run?await reconciliationService.run(id):await reconciliationService.getByDocument(id))}catch{setError('Không thể tải hoặc chạy đối soát cho chứng từ này.')}finally{setLoading(false)}};
 const decide=async(item:Reconciliation,status:'MATCHED'|'NEED_REVIEW')=>{if(!id)return;setPending(item.id);setError('');setMessage('');try{await reconciliationService.decide(id,item.id,status,note||undefined);setItems(await reconciliationService.getByDocument(id));setMessage('Đã lưu quyết định đối soát.');setNote('')}catch{setError('Không thể lưu quyết định; kết quả hiện tại vẫn được giữ nguyên.')}finally{setPending(null)}};
 return <div className="space-y-6"><PageHeader title="Đối soát chứng từ" description="Đối chiếu số liệu hóa đơn/chứng từ; không bao gồm sao kê ngân hàng." /><ContentCard className="p-5"><div className="flex flex-wrap gap-3"><input type="number" min="1" value={documentId} onChange={e=>setDocumentId(e.target.value)} placeholder="Mã chứng từ" className="rounded-lg border border-slate-300 px-3 py-2"/><button disabled={loading} onClick={()=>void load(false)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm disabled:opacity-50">Tải kết quả</button><button disabled={loading} onClick={()=>void load(true)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white disabled:opacity-50">Chạy đối soát</button></div></ContentCard>{message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{loading&&<LoadingState/>}{error&&<ErrorState message={error}/>} {!loading&&!error&&items.length>0&&<ContentCard><div className="border-b border-slate-200 p-4"><label className="text-sm text-slate-600">Ghi chú quyết định<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Tùy chọn" className="ml-3 rounded border border-slate-300 px-3 py-2"/></label></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-3">Kiểm tra</th><th className="p-3 text-right">Kỳ vọng</th><th className="p-3 text-right">Thực tế</th><th className="p-3 text-right">Chênh lệch</th><th className="p-3">Trạng thái</th><th className="p-3">Chi tiết</th><th className="p-3">Quyết định</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={item.status==='NEED_REVIEW'?'border-t border-amber-100 bg-amber-50/40':'border-t border-slate-100'}><td className="p-3 font-medium">{item.type}</td><td className="p-3 text-right">{money(item.expectedAmount)}</td><td className="p-3 text-right">{money(item.actualAmount)}</td><td className="p-3 text-right">{money(item.differenceAmount)}</td><td className="p-3"><span className={item.status==='MATCHED'?'rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-700':'rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-700'}>{item.status}</span></td><td className="p-3 text-slate-600">{item.comment||'-'}</td><td className="p-3"><div className="flex gap-2"><button disabled={pending!==null} onClick={()=>void decide(item,'MATCHED')} className="text-emerald-700 disabled:opacity-50">Khớp</button><button disabled={pending!==null} onClick={()=>void decide(item,'NEED_REVIEW')} className="text-amber-700 disabled:opacity-50">Cần xem</button></div></td></tr>)}</tbody></table></div></ContentCard>}{!loading&&!error&&documentId&&items.length===0&&<EmptyState title="Chưa có kết quả đối soát" description="Chạy đối soát để tạo kết quả."/>}</div>
}
export default ReconciliationWorkspace
