package com.example.invoice.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.example.invoice.dto.reconciliation.ReconciliationResponse; import com.example.invoice.entity.*; import com.example.invoice.exception.ResourceNotFoundException; import com.example.invoice.repository.*; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class ReconciliationServiceTest {
 @Mock DocumentService docs; @Mock InvoiceRepository invoices; @Mock ReconciliationRepository reconciliations; @Mock ReconciliationBatchRepository batches; @Mock UserService users;
 ReconciliationService service(){lenient().when(batches.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(reconciliations.save(any())).thenAnswer(i->i.getArgument(0));return new ReconciliationService(docs,invoices,reconciliations,batches,users);}
 Document doc(){Document d=new Document();d.setId(1L);Company c=new Company();c.setId(1L);d.setCompany(c);return d;} Invoice invoice(BigDecimal line,BigDecimal sub,BigDecimal vat,BigDecimal total){Invoice i=new Invoice();i.setInvoiceDate(java.time.LocalDate.now());i.setSubtotal(sub);i.setVatAmount(vat);i.setTotalAmount(total);InvoiceItem x=new InvoiceItem();x.setQuantity(new BigDecimal("1.0"));x.setUnitPrice(new BigDecimal("100.00"));x.setAmount(line);x.setTaxRate(new BigDecimal("10"));x.setTaxAmount(new BigDecimal("10"));i.setItems(List.of(x));return i;}
 @Test void exactMatchAndScaleAreMatched(){Document d=doc();when(docs.load(1L)).thenReturn(d);when(invoices.findByDocumentId(1L)).thenReturn(Optional.of(invoice(new BigDecimal("100.0"),new BigDecimal("100.00"),new BigDecimal("10"),new BigDecimal("110.00"))));when(users.loadCurrent(null)).thenReturn(new User());List<ReconciliationResponse> r=service().run(1L,null);assertTrue(r.stream().allMatch(x->"MATCHED".equals(x.status())));}
 @Test void itemSubtotalAndTotalMismatchesNeedReview(){Document d=doc();when(docs.load(1L)).thenReturn(d);when(invoices.findByDocumentId(1L)).thenReturn(Optional.of(invoice(new BigDecimal("90"),new BigDecimal("80"),new BigDecimal("10"),new BigDecimal("95"))));when(users.loadCurrent(null)).thenReturn(new User());List<ReconciliationResponse> r=service().run(1L,null);assertTrue(r.stream().filter(x->Set.of("ITEM_1_AMOUNT","SUBTOTAL","TOTAL").contains(x.checkType())).allMatch(x->"NEED_REVIEW".equals(x.status())));}
 @Test void decisionValidatesDocumentRelationAndStatus(){Reconciliation r=new Reconciliation();r.setId(2L);r.setDocument(doc());when(reconciliations.findById(2L)).thenReturn(Optional.of(r));when(docs.load(1L)).thenReturn(doc());when(users.loadCurrent(null)).thenReturn(new User());assertEquals("MATCHED",service().decide(1L,2L,"MATCHED","ok",null).status());assertThrows(IllegalArgumentException.class,()->service().decide(1L,2L,"BAD",null,null));assertThrows(ResourceNotFoundException.class,()->service().decide(9L,2L,"MATCHED",null,null));}
 @Test void missingItemsNeverReportsItemsOrAggregateAsMatched(){Document d=doc();Invoice i=invoice(BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO);i.setItems(List.of());when(docs.load(1L)).thenReturn(d);when(invoices.findByDocumentId(1L)).thenReturn(Optional.of(i));when(users.loadCurrent(null)).thenReturn(new User());List<ReconciliationResponse> r=service().run(1L,null);assertTrue(r.stream().filter(x->!"TOTAL".equals(x.checkType())).allMatch(x->"NEED_REVIEW".equals(x.status())));}
 @Test void rerunUpdatesExistingTypesInsteadOfCreatingDuplicates(){Document d=doc();Invoice i=invoice(new BigDecimal("100"),new BigDecimal("100"),new BigDecimal("10"),new BigDecimal("110"));Reconciliation old=new Reconciliation();old.setId(5L);old.setDocument(d);old.setComment("SUBTOTAL: old");ReconciliationBatch b=new ReconciliationBatch();old.setReconciliationBatch(b);when(docs.load(1L)).thenReturn(d);when(invoices.findByDocumentId(1L)).thenReturn(Optional.of(i));when(reconciliations.findByDocumentIdOrderByCreatedAtDesc(1L)).thenReturn(List.of(old));service().run(1L,null);verify(reconciliations).save(same(old));verify(batches,never()).save(any());}
 @Test void supportsEightAndTenPercentVatLines(){Document d=doc();Invoice i=new Invoice();i.setInvoiceDate(java.time.LocalDate.now());i.setSubtotal(new BigDecimal("200"));i.setVatAmount(new BigDecimal("18"));i.setTotalAmount(new BigDecimal("218"));InvoiceItem a=new InvoiceItem();a.setQuantity(BigDecimal.ONE);a.setUnitPrice(new BigDecimal("100"));a.setAmount(new BigDecimal("100"));a.setTaxRate(new BigDecimal("8"));a.setTaxAmount(new BigDecimal("8"));InvoiceItem b=new InvoiceItem();b.setQuantity(new BigDecimal("2"));b.setUnitPrice(new BigDecimal("50"));b.setAmount(new BigDecimal("100"));b.setTaxRate(new BigDecimal("0.10"));b.setTaxAmount(new BigDecimal("10"));i.setItems(List.of(a,b));when(docs.load(1L)).thenReturn(d);when(invoices.findByDocumentId(1L)).thenReturn(Optional.of(i));when(users.loadCurrent(null)).thenReturn(new User());List<ReconciliationResponse> result=service().run(1L,null);assertTrue(result.stream().allMatch(x->"MATCHED".equals(x.status())));assertEquals(2,result.stream().filter(x->x.checkType().endsWith("_VAT")).count());}
}
